all:
	make -C memo
	make -C pm_client
	make -C talker
	make -C probeagent

clean:
	make -C memo clean
	make -C pm_client clean
	make -C talker clean
	make -C probeagent clean

install:
	make -C memo install
	make -C pm_client install
	make -C talker install
	make -C probeagent install
